In [8]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import seaborn as sns

df = sns.load_dataset('diamonds').convert_dtypes(dtype_backend='numpy_nullable')
df.iloc[0,:] = None
table = pa.Table.from_pandas(df)
df2 = table.to_pandas()
df2 = df2

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53939 non-null  Float64
 1   cut      53939 non-null  category
 2   color    53939 non-null  category
 3   clarity  53939 non-null  category
 4   depth    53939 non-null  Float64
 5   table    53939 non-null  Float64
 6   price    53939 non-null  Int64
 7   x        53939 non-null  Float64
 8   y        53939 non-null  Float64
 9   z        53939 non-null  Float64
dtypes: Float64(6), Int64(1), category(3)
memory usage: 3.4 MB

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53939 non-null  Float64
 1   cut      53939 non-null  category
 2   color    53939 non-null  category
 3   clarity  53939 non-null  category
 4   depth    53939 non-null  Float64
 5   table    53939 non-null  Float64
 6   price    53939 non-null  Int64
 7   x        53939 non-null  Float64
 8   y        53939 non-null  Float64
 9   z        53939 non-null  Float64
dtypes: Float64(6), Int64(1), category(3)
memory usage: 3.4 MB

In [11]:
df2

       carat        cut color clarity  depth  table  price     x     y     z
0       <NA>        NaN   NaN     NaN   <NA>   <NA>   <NA>  <NA>  <NA>  <NA>
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334   4.2  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76   3.5
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937    0.7  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [12]:
# OK! this might be the way to do it
df2.convert_dtypes(dtype_backend='pyarrow').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53939 non-null  double[pyarrow]
 1   cut      53939 non-null  category
 2   color    53939 non-null  category
 3   clarity  53939 non-null  category
 4   depth    53939 non-null  double[pyarrow]
 5   table    53939 non-null  double[pyarrow]
 6   price    53939 non-null  int64[pyarrow]
 7   x        53939 non-null  double[pyarrow]
 8   y        53939 non-null  double[pyarrow]
 9   z        53939 non-null  double[pyarrow]
dtypes: category(3), double[pyarrow](6), int64[pyarrow](1)
memory usage: 3.1 MB

In [48]:
pd.DataFrame(table.to_py.convert_dtypes(dtype_backend='pyarrow').info()

SyntaxError: incomplete input (3183475315.py, line 1)

In [34]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  double[pyarrow]
 1   cut      53940 non-null  dictionary<values=string, indices=int8, ordered=0>[pyarrow]
 2   color    53940 non-null  dictionary<values=string, indices=int8, ordered=0>[pyarrow]
 3   clarity  53940 non-null  dictionary<values=string, indices=int8, ordered=0>[pyarrow]
 4   depth    53940 non-null  double[pyarrow]
 5   table    53940 non-null  double[pyarrow]
 6   price    53940 non-null  int64[pyarrow]
 7   x        53940 non-null  double[pyarrow]
 8   y        53940 non-null  double[pyarrow]
 9   z        53940 non-null  double[pyarrow]
dtypes: dictionary<values=string, indices=int8, ordered=0>[pyarrow](3), double[pyarrow](6), int64[pyarrow](1)
memory usage: 3.0 MB

In [35]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.11.2.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.2.0
Version               : Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.1.0
pip                   : 24.0
Cython                : None
pytest                : 8.0.0
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.21.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 15.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

/Users/aj/work/keepdb/env/lib/python3.11/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

KeyError: DictionaryType(dictionary<values=string, indices=int8, ordered=0>)