In [1]:
import keepdb
import seaborn as sns

In [2]:
keys = [
    'diamonds',
    'car_crashes',
]

dfs = {
    k: sns.load_dataset(k)
    for k in keys
}

In [3]:
keepdb.to_from.standard.dfs_to_zip('ajbah.zip', dfs)

In [4]:
dfs2 = keepdb.to_from.standard.zip_to_dfs('ajbah.zip')

In [5]:
dfs3 = keepdb.to_from.standard.zip_to_dfs('ajbah.zip', use_arrow_dtypes=True)

In [6]:
import pyarrow as pa
import pandas as pd

In [7]:
df = dfs2['diamonds']

In [42]:
def clean(df):
    return df.convert_dtypes(dtype_backend='numpy_nullable')

In [9]:
pa.Table.from_pandas(df, preserve_index=False).to_pandas(types_mapper)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  double[pyarrow]
 1   cut      53940 non-null  dictionary<values=string, indices=int8, ordered=0>[pyarrow]
 2   color    53940 non-null  dictionary<values=string, indices=int8, ordered=0>[pyarrow]
 3   clarity  53940 non-null  dictionary<values=string, indices=int8, ordered=0>[pyarrow]
 4   depth    53940 non-null  double[pyarrow]
 5   table    53940 non-null  double[pyarrow]
 6   price    53940 non-null  int64[pyarrow]
 7   x        53940 non-null  double[pyarrow]
 8   y        53940 non-null  double[pyarrow]
 9   z        53940 non-null  double[pyarrow]
dtypes: dictionary<values=string, indices=int8, ordered=0>[pyarrow](3), double[pyarrow](6), int64[pyarrow](1)
memory usage: 3.0 MB

In [18]:
dfs3['diamonds']

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334   4.2  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76   3.5
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937    0.7  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [44]:
# this is the bug we need to figure out

dfs3['diamonds'].convert_dtypes(dtype_backend='numpy_nullable').info()

KeyError: DictionaryType(dictionary<values=string, indices=int32, ordered=0>)

In [30]:
dfs2['diamonds'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

In [29]:
dfs3['diamonds'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  double[pyarrow]
 1   cut      53940 non-null  dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 2   color    53940 non-null  dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 3   clarity  53940 non-null  dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 4   depth    53940 non-null  double[pyarrow]
 5   table    53940 non-null  double[pyarrow]
 6   price    53940 non-null  int64[pyarrow]
 7   x        53940 non-null  double[pyarrow]
 8   y        53940 non-null  double[pyarrow]
 9   z        53940 non-null  double[pyarrow]
dtypes: dictionary<values=string, indices=int32, ordered=0>[pyarrow](3), double[pyarrow](6), int64[pyarrow](1)
memory usage: 3.5 MB

In [43]:
pd.testing.assert_frame_equal(
    clean(dfs2['diamonds']),
    clean(dfs3['diamonds']),
    check_dtype = False
)

KeyError: DictionaryType(dictionary<values=string, indices=int32, ordered=0>)

In [ ]:
pa.Table.from_pandas(x, preserve_index=False)

In [9]:


dfs2['diamonds']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

In [10]:
dfs3['diamonds'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  double[pyarrow]
 1   cut      53940 non-null  dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 2   color    53940 non-null  dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 3   clarity  53940 non-null  dictionary<values=string, indices=int32, ordered=0>[pyarrow]
 4   depth    53940 non-null  double[pyarrow]
 5   table    53940 non-null  double[pyarrow]
 6   price    53940 non-null  int64[pyarrow]
 7   x        53940 non-null  double[pyarrow]
 8   y        53940 non-null  double[pyarrow]
 9   z        53940 non-null  double[pyarrow]
dtypes: dictionary<values=string, indices=int32, ordered=0>[pyarrow](3), double[pyarrow](6), int64[pyarrow](1)
memory usage: 3.5 MB

In [14]:
keepdb.are_dfs_equal(dfs2['diamonds'], dfs3['diamonds'], check_dtype=True)

AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="carat") are different

Attribute "dtype" are different
[left]:  float64
[right]: double[pyarrow]

In [12]:
dfs2['diamonds']

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]